layout_spectrum: 0.1612903
color:
  saturation: 0.7731724
  brandStrength: 0.201167
  lightness: 0.6612903
  rhythmicContrast: 0.1295201
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0
name: Joanneppf
